[versions]
androidxCore = "1.9.0"
androidxTestCore = "1.5.0"
androidxTestExt = "1.1.4"
androidxTestRunner = "1.5.1"
androidxTestRules = "1.5.0"
androidxTracing = "1.1.0"
androidxUiAutomator = "2.2.0"
androidxCoreSplashscreen = "1.0.0"
androidxWork = "2.7.1"
accompanist = "0.28.0"
androidGradlePlugin = "8.1.0-alpha05"
appCompat = "1.5.1"
activityCompose = "1.6.1"
coil = "2.2.2"
composeDestination = "1.7.25-beta"
composeVersion = "1.4.0-alpha02"
composeAlpha = "1.1.0-alpha02"
composeCompiler = "1.4.0"
composeRuntimeTracing = "1.0.0-alpha01"
constraintLayout = "1.1.0-alpha04"
coroutines = "1.6.4"
dataStore = "1.0.0"
dokka = "1.7.10"
espresso = "3.5.0"
googleMaterial = "1.7.0"
gson = "2.10"
hiltNavigationCompose = "1.0.0"
hilt = "2.44.2"
hiltExt = "1.0.0"
jacoco = "0.8.7"
junit4 = "4.13.2"
kotlin = "1.8.0"
kotlinxDatetime = "0.4.0"
kotlinxSerializationJson = "1.4.1"
ksp = "1.8.0-1.0.9"
kotlinxImmutable = "0.3.5"
lifecycle = "2.6.0-alpha03"
lint = "30.3.1"
materialMotion = "0.11.0-alpha"
pagingCompose = "1.0.0-alpha17"
pagingRuntime = "3.2.0-alpha03"
okhttp = "4.10.0"
retrofit = "2.9.0"
retrofitKotlinxSerializationJson = "0.8.0"
room = "2.5.0-beta02"












[libraries]
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanist" }



android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintLayout" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-paging-runtime =  {group = "androidx.paging" , name = "paging-runtime", version.ref = "pagingRuntime" }
androidx-paging-compose =  {group = "androidx.paging" , name = "paging-compose", version.ref = "pagingCompose" }



compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "composeVersion" }
compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "composeVersion" }
compose-destination = { group = "io.github.raamcosta.compose-destinations", name = "animations-core", version.ref = "composeDestination" }
compose-destination-ksp = { group = "io.github.raamcosta.compose-destinations", name = "ksp", version.ref = "composeDestination" }
compose-material-icons-full = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "composeAlpha" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "composeVersion" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeAlpha" }
compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "composeAlpha" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "composeVersion" }
compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "composeVersion" }
compose-runtime-tracing = { group = "androidx.compose.runtime", name = "runtime-tracing", version.ref = "composeRuntimeTracing" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "composeVersion" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "composeVersion" }
compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "composeVersion" }
compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "composeVersion" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "composeVersion" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeVersion" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "composeVersion" }
compose-ui-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "composeVersion" }

coil-kt = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-kt-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-kt-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }


dataStore-core = { group = "androidx.datastore", name = "datastore", version.ref = "dataStore" }
dataStore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }

google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }

hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-ext-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltExt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }



kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxImmutable" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

lint-api = { group = "com.android.tools.lint", name = "lint-api", version.ref = "lint" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-viewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }

material-motion = { group = "io.github.fornewid", name = "material-motion-compose-core", version.ref = "materialMotion" }

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinxSerializationJson" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }


symbol-processing-gradle-plugin = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }
test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
test-junit = { group = "junit", name = "junit", version.ref = "junit4" }
test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidxUiAutomator" }

work-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWork" }
work-testing = { group = "androidx.work", name = "work-testing", version.ref = "androidxWork" }



[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
















